### PR TITLE
Physical Flow table should use flow ext id

### PR DESCRIPTION
**Pull request by davidwatkins73**
- not the spec ext id

#4891

### CODE REVIEW

**Comment by davidwatkins73** [comment]
@rovats - could you take a quick look ?  keen to get this through (or fixed if broken)

**Comment by davidwatkins73** [comment]
Rohit - I've speculatively merged - we can back out if I got it wrong - but since it was such a small change I think it's ok

**Comment by rovats** [comment]
Looks good, thanks Dave.

Btw, just noticed that some of the fields in PhysicalFlowExtractor have *NAR* in them: eg: `SOURCE_NAME_AND_NAR_FIELDS`

**Comment by davidwatkins73** [comment]
Thanks  - will submit a quick fix.

**Pull request merged**
