### PR TITLE
Lp contrib/waltz 6852 oauth sso framework

### PR DESCRIPTION
**Pull request by TL41**
### Contribution Notes:
@davidwatkins73 I'd like to submit this as a contribution from Leading Point (team effort - Thomas Ledger (@TL41), Oscar Green (@OscarGreen03), Karen Wen ([@kwen](https://github.com/kwen0))

Let me know if you would like to discuss these changes. I've detailed the implementation of optional changes and some changes which I'm not entirely sure would be compatible if the ```web.authentication``` method is set to ```waltz```; for obvious reasons, we've committed to ```sso``` so we haven't been testing thoroughly for ```waltz``` compatibility.

for: https://github.com/finos/waltz/issues/6852

---
### Explanation:
* waltz-ng/client/common/[WaltzHttp.js](./common/WaltzHttp.js) <-- optional enhancement(s) to catch and revoke token
* waltz-ng/client/navbar/[svelte-page.html](./navbar/svelte-page.html) <-- optional enhancement to block access to Waltz if not authenticated/authorized
* waltz-ng/client/navbar/[svelte-page.js](./navbar/svelte-page.js) <-- did not include the $auth.authenticate("oauthprovider") code because I believe it would get invoked regardless of which ```web.authentication``` method was selected; and that would not be ok if ```waltz``` was selected
* waltz-ng/client/svelte-stores/[remote.js](./svelte-stores/remote.js) <-- optional enhancement(s) to catch and revoke token
* waltz-ng/client/[thirdparty-setup.js](./thirdparty-setup.js) <-- optional enhancement(s) to catch and revoke token
* waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/[AuthenticationEndpoint.java](../../waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java)

Additional edits make to integrate this solution into the waltz.properties files and enhanced those files with comments (happy to back those out)

### Future Enhancements:
* seamless integration of environment specific thirdparty-setup configurations for OAuth (i.e. different url for Dev, QA, Prod envs)
* single implementation compatible with both ```web.authentication``` method

### CODE REVIEW

**Comment by TL41** [comment]
@davidwatkins73 after our discussion, I want to revise the framework to make it more seamlessly compatible with cases where the `web.authentication` method is set to `waltz`, and also cases where `web.authentication` method is set to `sso` but the instance might be implementing sso without using the satellizer setup.

I'll be making a lot of revisions to get that done

**Comment by TL41** [comment]
@davidwatkins73 I have a working version of the changes for a set of changes that's compatible with `waltz` and `sso` options, configurable via the database. It would also work with `sso` solutions that are _not_ currently leveraging thirdparty-setup.js

I'll look to get this submitted here in the next few days

**Comment by davidwatkins73** [comment]
Hi @TL41 , I've been doing some simple experiments on how best to configure the authentication provider at runtime rather than at build time.  I've attached a patch with a _very_ basic example of an approach that looks promising.

[silly_example.patch](https://github.com/finos/waltz/files/13505708/silly_example.patch)

At a high level all we are doing is using a script tag on the `index.ejs`  (in the example `<script src='api/silly'></script>`) file to import some javascript from the server.  However, this script is dynamically generated in Java  and simply emits a variable declaration with some attributes (e.g. (`get("api/silly", (req, resp) -> { .... });`) .  

If this approach was adopted, the generated variable could be a slice of any values in the `settings` table with a certain  prefix, e.g. `waltz.authentication.config.public.*`, the resulting dynamic script could be something like:

```
const waltzAuthenticationConfig = {
   'prop1': 'val1',
   'prop2': 'val2'
};
```

As this, dynamically generated, script is included via a script tag on the main index page (`index.ejs`) it gets evaluated before the rest of the code starts executing and the variable (`waltzAuthenticationConfig`) would be _globally_ available (as demo'd in the patched `thirdparty-setup.js`).  

This approach seems quite straightforward and I think gives us a good way of dynamically including the required configuration.

**Comment by TL41** [comment]
@davidwatkins73 I've added changes to `svelte-page.js` to pull the oauth configuration setup (not the *details*) from the database. I've updated the documentation to highlight 3 valid configurations:

* Waltz Login
	* ```web.authentication``` = ```waltz```
	* ```oauth.provider.name```  <-- do not add to Settings
	* ```oauth.disable.anonymous``` <-- do not add to Settings
* SSO (Externally Managed)
	* ```web.authentication``` = ```sso```
	* ```oauth.provider.name``` <-- do not add to Settings
	* ```oauth.disable.anonymous``` <-- do not add to Settings
* SSO (thirdparty integration with satellizer)
	* ```web.authentication``` = ```sso```
	* ```oauth.provider.name``` needs to match the 'name' you provide in thirdparty-setup.js
	* ```oauth.disable.anonymous``` can be set to ```true`` (blocks anonymous browsing) or ```false``` (allows anonymous browsing) or left out of Settings (allows anonymous browsing)

I've tested this locally and with a thirdparty provider and it seems to be working.

Here's a checklist of what I think remains:
- [ ] Review changes to waltz-ng/client/common/WaltzHttp.js - should this token exception check be included?
- [ ] Review waltz-ng/client/svelte-stores/remote.js - should this token exception check be included?
- [ ] Review waltz-ng/client/navbar/svelte-page.html
- [ ] Review waltz-ng/client/navbar/svelte-page.js
- [ ] Review waltz-ng/client/thirdparty-setup.js - is this ok as an interim solution? (define environment specific configs here and then build)
- [ ] Related to previous item: do we take the time now to implement a dynamic oauth configuration? (we may also be able to leverage SatellizerConfig (some examples in the repo - https://github.com/sahat/satellizer/issues/658)
- [ ] Review waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java

**Comment by TL41** [comment]
@davidwatkins73 I tested out the changes for exception handling on the sso JWT, and it didn't seem like the logic was getting invoke. I don't think this is a core feature required right now, so I'm removing that from the scope of this PR and opened an issue to track it for future implementation, if at all. https://github.com/finos/waltz/issues/6913

Here's a checklist of what I think remains:
- [x] Review waltz-ng/client/navbar/svelte-page.html
- [x] Review waltz-ng/client/navbar/svelte-page.js
- [x] Review waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java
- [ ] Build an externally parameterized/configurable oauth2 provider implementation (could be within thirdparty-setup; via api idea from David W; using SatellizerConfig, etc)
- [ ] Review and test complete solution

**Comment by TL41** [comment]
@davidwatkins73 submitting a final solution for thirdparty Oauth provider integration using satellizer

I know you proposed adding individual records into Settings for the individual key-value pairs to build oauth.provider.details, but I'm implementing this solution as a single entry in settings called ```oauth.provider.details``` which would contain the entire object. I think it would be a bit onerous for the user to have to add 15-20 individual settings. I'm open to changing this in the future to be more dynamic, but for now my object is under 1000 chars so it fits comfortably into the Settings table

Here's a checklist of what I think remains:
- [x] Review waltz-ng/client/navbar/svelte-page.html
- [x] Review waltz-ng/client/navbar/svelte-page.js
- [x] Review waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java
- [x] Build an externally parameterized/configurable oauth2 provider implementation (could be within thirdparty-setup; via api idea from David W; using SatellizerConfig, etc)
- [x] Review and test complete solution

--- 
Final details:
* Waltz Login
	* ```web.authentication``` = ```waltz```
	* ```oauth.provider.name```  <-- do not add to Settings
    * ```oauth.provider.details```  <-- do not add to Settings
	* ```oauth.disable.anonymous``` <-- do not add to Settings
* SSO (Externally Managed)
	* ```web.authentication``` = ```sso```
	* ```oauth.provider.name``` <-- do not add to Settings
    * ```oauth.provider.details```  <-- do not add to Settings
	* ```oauth.disable.anonymous``` <-- do not add to Settings
* SSO (thirdparty integration with satellizer)
	* ```web.authentication``` = ```sso```
    * ```oauth.provider.details```  = object containing thirdparty OAuth Provider details  
	* ```oauth.provider.name``` needs to match the 'name' you provide in `oauth.provider.details`
	* ```oauth.disable.anonymous``` can be set to ```true`` (blocks anonymous browsing) or ```false``` (allows anonymous browsing) or left out of Settings (allows anonymous browsing)

**Review by TL41 — COMMENTED** [review]
reviewed changed files - seems to be as expected

**Comment by TL41** [comment]
@davidwatkins73 let me know if you would like to discuss this sometime. I would like to see it make it's way into the next release.

The solution should have no impact on existing installations. The logic should only kick in if you were to define and enable the 3 new settings

**Comment by davidwatkins73** [comment]
Took a look at this and it looks good.  Had a couple of small issues where I needed to provide some dummy values to get Waltz to start.  

I've put some fixes for those issues (and some, hopefully trivial, additional changes in this PR:   #6935 

....specifically this commit: https://github.com/finos/waltz/pull/6935/commits/268b79f5ebf2c0d382879c5a94ccae01914e8be6

**Comment by TL41** [comment]
@davidwatkins73 thanks for the revisions!  Feel free to merge and I'll look to test it out early this week. 

If it's not 100% working for us at the moment, we're no worse off then where we were (having to build off a separate branch with additional changes) - my point being - if it works for you all in this state, don't let it hold up your release. 

Of course we can try to work it out in the coming day, and if not, we can work on a new effort to get this as a universal solution in another release.

**Comment by davidwatkins73** [comment]
Merged.  Thanks for this great contribution!

**Pull request merged**
